name: Update website
on:
  push:
    branches:
      - modernise-js
  # Allow running manually from the Actions tab (useful if there are changes to
  # snowball and/or snowball-data that affect the website).
  workflow_dispatch:

permissions:
  contents: write
jobs:
  update-website:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout snowball
        uses: actions/checkout@v3
        with:
          repository: snowballstem/snowball
          path: snowball

      - name: Checkout snowball-data
        uses: actions/checkout@v3
        with:
          repository: snowballstem/snowball-data
          path: snowball-data

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libipc-run-perl libtemplate-perl graphviz pngcrush python3-pygments
          #npm i -g google-closure-compiler
          #perl -pi -e '/--accept_const_keyword/ and $_="";s/closure-compiler/google-closure-compiler/;s/ADVANCED_OPTIMIZATIONS/ADVANCED/' generate
          npm install uglify-js -g

      - name: Build snowball
        run: |
          mv snowball ../snowball
          mv snowball-data ../snowball-data
          cd ../snowball
          make -sj2

      - name: Generate
        run: |
          mkdir ../snowballstem.github.io
          ./generate
          mv dist ../snowballstem.github.io
          cd ../snowballstem.github.io
          find . -name '*.tt' -delete
          rm js/demo.js js/*-stemmer.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../snowballstem.github.io
          git-config-email: "<>"
          branch: gh-pages-modern-js
